### ISSUE TITLE
[Feature Request] Checking to see about support for Foundry V10

### ISSUE THREAD

**Issue by RinVindor** [p4535992/spellbook-master#1]
Just wanted to say thanks for making sure this still works since the original author isn't. I use this module constantly.

**Comment by sharkbruhaha** [comment]
```msdos
FoundryVTT | 2022-11-04 15:31:04 | [error] Metadata validation failed for module "spellbook-master": The file "languages/en.json" included by module spellbook-master does not exist
Error: Metadata validation failed for module "spellbook-master": The file "languages/en.json" included by module spellbook-master does not exist
    at PackageAssetField.initialize (file:///FoundryVTT-10.288/resources/app/dist/packages/package.mjs:1:1270)
    at SchemaField.initialize (file:///FoundryVTT-10.288/resources/app/common/data/fields.mjs:435:23)
    at file:///FoundryVTT-10.288/resources/app/common/data/fields.mjs:857:40
    at Array.map (<anonymous>)
    at SetField.initialize (file:///FoundryVTT-10.288/resources/app/common/data/fields.mjs:857:18)
    at SetField.initialize (file:///FoundryVTT-10.288/resources/app/common/data/fields.mjs:908:26)
    at Module._initialize (file:///FoundryVTT-10.288/resources/app/common/abstract/data.mjs:198:27)
    at new DataModel (file:///FoundryVTT-10.288/resources/app/common/abstract/data.mjs:60:10)
    at new BasePackage (file:///FoundryVTT-10.288/resources/app/common/packages/base-package.mjs:61:5)
    at new BaseModule (file:///FoundryVTT-10.288/resources/app/common/packages/base-module.mjs:11:16)
FoundryVTT | 2022-11-04 15:31:04 | [info] PACKAGE.InstallFailed - 100%
```

**Comment by sharkbruhaha** [comment]
unable to install on v10

**Comment by sharkbruhaha** [comment]
deleting the following from the module.json makes it load:
```json
    "languages": [
        {
            "lang": "en",
            "name": "English",
            "path": "./languages/en.json"
        }
    ],
```
